### ISSUE TITLE
trying to run ControlFloor

### ISSUE THREAD

**Issue by kpalczewski** [nanoscopic/controlfloor#1]
Hi,
I can't manage to edit main.go properly or I don't know how to compile it.
I edit line:
`r.Run( ":8080 )`
to:
`r.Run( "localhost:8080 )`
or
`r.Run( "127.0.0.1:8080 )`

Then I enter command
`go build`
and
`go run main.go`

but I get error:
`go: reading main.go: unexpected NUL in input`

Can you please tell me what the culprit might be?

**Comment by himanshunamdeo** [comment]
1. Alter `main.go`. Add hostname, Eg. `r.Run( "127.0.0.1:8080 )`
2. Build the controlfloor module by `make` command. It will download certain dependencies.
3. After that run the module by `./main`. This will start all the services and module will start listening on local host.
4. On your browser address box enter `http://localhost:8080`. It should show you the interface.

**Comment by nanoscopic** [comment]
Without the hostname added, ControlFloor simply listens on all interfaces. If you do set a hostname, it has to match what you request in the browser. If confused, add the hostname as @himanshunamdeo says.

It appears you are missing the ending double quote ( " ) in the lines you have shown.

**Comment by kpalczewski** [comment]
gotta love those errors :disappointed: 
Thank you for your help. I managed to compile it properly.
