### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by nanoscopic** [nanoscopic/controlfloor#13]
Add full straight Linux support.

This is multipart:
1. Using alibaba tidevice instead of iosif on Linux. ( possible due to newly create bridge interface )
2. Possibly integrating a resigning system. This isn't really necessary but will remove the need to actually build on MacOS with new updates. Would prefer this to remove manual steps to rebuild on MacOS and then deploy from there. Users should be able to update directly on Linux without touching a MacOS system.

**Comment by nanoscopic** [comment]
I began attempting to port iosif to Linux using libimobiledevice. It can be done but is more effort than I initially estimated. The way libimobiledevice is different in a number of ways from mobiledevice framework by Apple.

The faster solution remains to use tidevice / go-ios to get it running on Linux more quickly.

**Comment by nanoscopic** [comment]
The provider has now been updated to use go-ios instead of iosif by default. It should now run on Linux. I haven't yet tested it though there, so not closing this issue yet.

**Comment by nanoscopic** [comment]
Have now tested the provider on Linux and it is working fine. I did have to make a few minor changes though to get it running; will commit and push those changes and add documentation. MacOS is no longer required to run CF!

**Comment by suidpit** [comment]
Hello @nanoscopic and thanks for your amazing work here! I see it should be possible to run CF from a Linux machine; how does that work in the ios remote provider with the steps where WDA has to be built with xcode? Does that still require a macOS machine to build WDA for the device and then install it via linux, or do you already have a way to do this without a macOS machine?

**Comment by nanoscopic** [comment]
The WDA and the video app both need to be built in Xcode on MacOS. If you don't have a MacOS machine you could use something such as docker-osx to run MacOS on a Linux machine and build it that way. I will be providing prebuilt versions of both apps in the near future.

You cannot directly use prebuilt versions. They would still need to be signed with a MacOS developer account provisioning profile. Various open source app resigning tools could be used to do that.

Many various open source tools can be used to install both apps on your iOS device from Linux. I would reccomend go-ios for this purpose. `go-ios install --path [something.app] --udid [device udid]` You will need to mount the appropriate developer image for your device on Linux first as well `go-ios image auto --udid [device udid]`. That mount must be done on every reboot of your iOS device.

**Comment by shamanec** [comment]
Hey, @nanoscopic, can we get some updated steps/guide on getting the project running on Linux? I want to attempt to dockerize it because of, you know, cheap hardware... 😅

**Comment by nanoscopic** [comment]
Full Linux support exists in the closed-source version. It is unlikely to be open-sourced again for at least a year or two looking how things are going. Essentially port all the calls not using go-ios to iosif and it works. That's what I did.

If someone does so I'll merge the PR. Otherwise nope. Closing.
