### ISSUE TITLE
findXctestrun panics with nil pointer dereference

### ISSUE THREAD

**Issue by NguyenHoangDuy2406** [nanoscopic/controlfloor#17]
Hi,
I'm following the guideline you gave and already complete 90% (device was already listed on Control Floor). But when I run the cli `./main run` for ios_remote_provider, I received error below:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x433a501]
> goroutine 28 [running]:
> main.findXctestrun.func1(0x0, 0x0, 0x0, 0x0, 0x445f4e0, 0xc000310330, 0x0, 0x0)
	/Users/cbvn-mac04/Documents/ios_remote_provider/wda.go:94 +0x41
> path/filepath.Walk(0x0, 0x0, 0xc0002990b0, 0x0, 0x445f4e0)
	/usr/local/Cellar/go@1.15/1.15.8/libexec/src/path/filepath/path.go:404 +0x6b
> main.findXctestrun(0x43ed441, 0x9, 0x1, 0x1)
	/Users/cbvn-mac04/Documents/ios_remote_provider/wda.go:93 +0xc8
> main.(*WDA).start(0xc0000b3560)
	/Users/cbvn-mac04/Documents/ios_remote_provider/wda.go:53 +0x96
> main.NewWDA(0xc0000b23c0, 0xc0000ba780, 0xc000328000, 0x1fa6, 0x4409010)
	/Users/cbvn-mac04/Documents/ios_remote_provider/wda.go:42 +0x165
> main.(*Device).startProcs(0xc000328000)
	/Users/cbvn-mac04/Documents/ios_remote_provider/device.go:185 +0x50
> main.(*DeviceTracker).onDeviceConnect1(0xc0000ba780, 0x44689c0, 0xc00007a040, 0xc0003121a0)
	/Users/cbvn-mac04/Documents/ios_remote_provider/device_tracker.go:95 +0x3b4
> main.NewDeviceTracker.func1(0x44689c0, 0xc00007a040, 0xc000028060, 0x28)
	/Users/cbvn-mac04/Documents/ios_remote_provider/device_tracker.go:38 +0x3e
> main.(*IIFBridge).OnConnect(0xc0000d06c0, 0xc000028060, 0x28, 0xc0000220c0, 0x12, 0xc0000bdc00)
	/Users/cbvn-mac04/Documents/ios_remote_provider/bridge_iif.go:85 +0xc8
> main.(*IIFBridge).startDetect.func2(0xc00007e000, 0x5a, 0xc0000bdc00)
	/Users/cbvn-mac04/Documents/ios_remote_provider/bridge_iif.go:61 +0x2e9
> main.proc_generic.func1(0xc0000bdc00, 0xc000156420, 0xc00010c300, 0xc000156360, 0xc0001563f0, 0xc00008e660, 0xc0000b4ba0, 0x0, 0x0)
	/Users/cbvn-mac04/Documents/ios_remote_provider/proc_generic.go:189 +0xd94
created by main.proc_generic
	/Users/cbvn-mac04/Documents/ios_remote_provider/proc_generic.go:105 +0x626
	
Could you help me on that error?
Thank you so much!

**Comment by nanoscopic** [comment]
wda.go:94 ( https://github.com/nanoscopic/ios_remote_provider/blob/main/wda.go#L94 ) is part of the recursive file search that attempts to location the created "xctestrun" file that is part of the built WebDriverAgent within the bin/wda folder.

`bin/wda` is actually a symlink to `repos/WebDriverAgent/build/Build/Products/`

If the Makefile succeeded in cloning and building WebDriverAgent, then this folder would exist and contain the xctestrun file.

I can add code that protects the search from crashing here, but it won't fix the root issue that is likely that WebDriverAgent did not build.

Look in the `repos/WebDriverAgent/build/Build/Products/` folder. Does that folder even exist? What is in that folder after you run `make`?

Do have have a paid Apple developer account? Have you configured your OU in the `config.json` file before running make? What is within your `config.mk` file?

The Makefile process is somewhat finicky and can break easily if you ran `make` before setting `config.json` options. I'd recommend deleting `config.mk` and running `make` again.

**Comment by NguyenHoangDuy2406** [comment]
Hi @nanoscopic 
I've fixed that. It's failed because some repo can't get when you set in MakeFile. Ex: ${config_repos_iosif}, ${config_repos_vidapp},... I must add some lines on the beginning of MakeFile:
`config_repos_wda := "https://github.com/appium/WebDriverAgent.git"`
`config_repos_iosif := "https://github.com/nanoscopic/iosif.git"`
`config_repos_vidapp := "https://github.com/nanoscopic/ios_video_app.git"`
`config_repos_pbxproj := "https://github.com/kronenthaler/mod-pbxproj"`
`config_repos_ujsonin := "https://github.com/nanoscopic/ujsonin.git"`

And also we had an typing error at:
`repos/ujsonin: git clone ${config_repos_ujsonin} repos/jsonin`

It should be:
`repos/ujsonin: git clone ${config_repos_ujsonin} repos/ujsonin`

Thank you very much for investigate this solution. Hope to see it's improve more ^^.


P/S: one more thing I want to ask -> if we broadcast (recording) on iOS device like this solution do, do we have any limit on it? Like the broadcast will close after xx minutes or something like this.

**Comment by nanoscopic** [comment]
findXctestrun is no longer used whatsoever. go-ios is now used to start WDA ( WDA must be pre-installed to device )

In the near future ( next few days ) I am adding an option additionally to use tidevice instead of go-ios if desired.

**Comment by nanoscopic** [comment]
Option to use tidevice was added and is reliable.
