### ISSUE TITLE
Error running `ios_remote_provider/main -register`

### ISSUE THREAD

**Issue by stamhaney** [nanoscopic/controlfloor#18]
@nanoscopic 
When I am trying to run the registration command: ./main register while setting up the ios_remote_provider, and press enter on the input field, I am getting the following error:

$ ./main register
Enter registration password:
Using default registration password of doreg
panic: runtime error: index out of range [48] with length 48

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/mod.Parse(0xc000190000, 0x30, 0x600, 0xc000190000, 0x30, 0x600, 0x0)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/ujsonin@v1.13.0/mod/ujsonin.go:369 +0x1f83
main.doregister(0xc000068420, 0x0, 0x0)
/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/controlfloor.go:419 +0x565
main.runRegister(0xc000072230)
/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/main.go:46 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc00015de50)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x240
main.main()

Can you please help

**Comment by NguyenHoangDuy2406** [comment]
It's DUP with https://github.com/nanoscopic/controlfloor/issues/17. It's because the WDA was installed and set up completed.

You can check the folder repos/WebDriverAgent/build. It should include all items like it:
![Screen Shot 2021-03-05 at 12 33 18](https://user-images.githubusercontent.com/1097668/110071646-f863be80-7dae-11eb-8ac1-79e2700b3edc.png)

**Comment by rub-code** [comment]
Hi @nanoscopic 

Thank You for your reply, I have verified that folder structure is as per your suggestion.

$ ./main register
Enter registration password:alpha
panic: runtime error: index out of range [48] with length 48

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/mod.Parse(0xc000124000, 0x30, 0x600, 0xc000124000, 0x30, 0x600, 0x0)
	/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/ujsonin@v1.13.0/mod/ujsonin.go:369 +0x1f83
main.doregister(0xc0000aa3c0, 0x0, 0x0)
	/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/controlfloor.go:419 +0x565
main.runRegister(0xc0000b01e0)
	/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/main.go:46 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
	/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc000105e50)
	/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x240
main.main()
	/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/main.go:20 +0x31a


**As you have suggested to check folder hierarchy, It is as expected shared screenshot for your reference**

Kindly help.

Sharing screenshot with you for your reference.

![IMG-20210308-WA0017](https://user-images.githubusercontent.com/80237745/110295106-ba68d380-8016-11eb-9ab9-3dc2b231d484.jpg)

**Comment by nanoscopic** [comment]
Things have been changed a bunch since this. I never saw this particular issue though. Please run again with latest code and state whether this issue still occurs for you and I will look into it if so.

If it works now for you please close this issue.

**Comment by rub-code** [comment]
Looping Rajeev,

 

Thanks & Regards,

Rubina Mulani

**Comment by nanoscopic** [comment]
If it is helpful I could create a video demonstrating initial setup of a functioning ControlFloor system.

It doesn't take very long to do that. I have been meaning to do it anyway as many users would be helped by this.

It should not be difficult just to get the basic system up and running, and I fear that my instructions are just not clear.

With a video, you could see exactly what must be done.

**Comment by rub-code** [comment]
Thanks @nanoscopic 

Yes Please it would be great help. :)

**Comment by nanoscopic** [comment]
I don't understand what the issue was here. This issue is non-actionable. Steps explaining how to duplicate this problem would need to be given. I'm chalking this up to user error / failure to follow instructions on system setup for now.

There were also problems with various versions of ujsonin previously; but those are all fixed now.

Eg: This was an issue but was fixed long ago and kept open and commented on by others for non-relevant issues to the posted problem.
