### ISSUE TITLE
device co-ordinates issue

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/controlfloor#20]
Hi, The iPhone7 seems to work fine with respect to click, swipe, etc.. but the same thing doesn't work for iPad, iPhone XR, any clues on how can we make it work for all the devices.

Thanks.

**Comment by nanoscopic** [comment]
The main reason for this is I don't have any newer iPhones myself past iPhone 7. If someone would like to send me newer devices I'd be happy to figure out what is going on with them and get them working correctly. This is only partly a joke...

Joking aside, it is my understanding that the "click resolution" is equal to the physical resolution divided by the "screen scale". Eg: the output of `iosif mg main-screen-width main-screen-height main-screen-scale`

When clicking, what happens is that those numbers are used to determine what positions to send to WebDriverAgent when clicking/swiping.

I do have a newer iPad ( iPad Air 3 ); I have not tried it recently to see what happens. Last time I tried ( 3+ months ago ) it was working correctly for clicking/swiping.

What is the iOS version and exact models of the devices that are not working for you, along with the output of the `iosif mg` command I mention here?

I'll need to know also if clicking/swiping simply doesn't work at all, or if it the calculation of where to click is off. Are you able to click on things on screen, but the offset is wrong? ( eg; click happens but not where you intended? )

**Comment by sai-tirunagiri** [comment]
@nanoscopic you have got some good sense of humor! well, 

> I'll need to know also if clicking/swiping simply doesn't work at all, or if it the calculation of where to click is off. Are you able to click on things on screen, but the offset is wrong? ( eg; click happens but not where you intended? )

You are correct, the offset which is being calculated for different devices with bigger and medium screens is wrong.

my XR device, iosif mg has the following output
```
json:{
"main-screen-width":750,
"main-screen-height":1334,
"main-screen-scale":2
}
```

And the below is for the iPad 6th gen
```
json:{
"main-screen-width":1536,
"main-screen-height":2048,
"main-screen-scale":2
}
```

**Comment by plaguez137** [comment]
Hi @nanoscopic, just adding my observations to this issue.

I'm using an iPhone 8 Plus at 13.6.1.  Clicks are not lining up, but seem to be offset, and maybe scaled inaccurately as well, as I'm able to "find" the right place to click, usually below and right of the target.  I'm not able to click anything near the bottom of the screen.  My iosif output:
```
{
"main-screen-width":1080
,
"main-screen-height":1920
,
"main-screen-scale":3

}
```

Can you let me know if there is something I can configure to try to correct it until you've solved it?

Thanks for the great work you're doing with this project.

**Comment by sai-tirunagiri** [comment]
@plaguez137 - What I have done to work around this is, get the device height and width also, take the device height and width divide by scale to make this dynamic so that any device you connect will not have issues with co-ordinates.

**Comment by nanoscopic** [comment]
Documentation on this was added to the ios_remote_provider repo.
Clicking coordinates work properly following those instructions.
I'd like it to happen automatically and require no manual steps but the manual steps are easy enough and work for now.
