### ISSUE TITLE
Control floor breaks at some point during the day

### ISSUE THREAD

**Issue by kristeedev** [nanoscopic/controlfloor#21]
Noted that Control floor is breaking at times during the day.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x45da7de]

goroutine 203 [running]:
github.com/gorilla/websocket.(*Conn).Close(...)
        /Users/lab_macmini/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:344
main.handleImgProvider.func1(0xc00032e280)
        /Users/lab_macmini/Documents/mobile_testing/controlfloor/provider.go:339 +0x3e
created by main.handleImgProvider
        /Users/lab_macmini/Documents/mobile_testing/controlfloor/provider.go:336 +0x335

**Comment by sai-tirunagiri** [comment]
The latest release has retry capability just in case if the WebSocket breaks, by the way, may I know how controlfloor and ios_remote_provider hosted.?

is controlfloor hosted on some remote machine.

**Comment by gkrananth** [comment]
I am getting this issue while trying to control the iPhone, am trying with my local machine.

**Comment by nanoscopic** [comment]
Is this still happening for anyone?

**Comment by man4567890** [comment]
I do not know if it is the same problem, this is what I'm getting, so I start everything up, see the logfiles.
I have a minimac and a Centos 7 sever running, the logfile server.log is the log from the Centos 7 server and the logfile minimac.log is from the minimac where the iPhone is plugged in. All works, but then if I leave it without any activity for 5min or so and I start swiping again, I can see the swipes come through in the logfile, but the video is not updated. I have to refresh in the browser to get the video to display again. I've attached a video demonstrating the behavior
[minimac.log](https://github.com/nanoscopic/controlfloor/files/7283329/minimac.log)
[server.log](https://github.com/nanoscopic/controlfloor/files/7283335/server.log)

https://user-images.githubusercontent.com/53390181/135972289-e1faa69c-4c2b-420a-8304-b0a9ce2862cc.mp4

This is how I start Control Floor on the Centos server using systemctl 

```
[root@networks168 ~]# systemctl status control-floor.service 
● control-floor.service - The Control Floor Server
   Loaded: loaded (/usr/lib/systemd/system/control-floor.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-10-05 08:05:42 SAST; 32min ago
 Main PID: 10685 (start_control-f)
   CGroup: /system.slice/control-floor.service
           ├─10685 /bin/bash /var/www/html/controlfloor/start_control-floor.sh &
           └─10710 ./main run

Oct 05 08:05:42 networks168.networks.com systemd[1]: Started The Control Floor Server.
[root@networks168 ~]# cat /usr/lib/systemd/system/control-floor.service
[Unit]
Description=The Control Floor Server
After=multi-user.target

[Service]
Restart=always
ExecStart=/var/www/html/controlfloor/start_control-floor.sh &

[Install]
WantedBy=multi-user.target

[root@digitatanetworks168 ~]# cat /var/www/html/controlfloor/start_control-floor.sh
#!/bin/bash
#This starts control floor for Apple devices

mkdir -p /var/log/control-floor/
echo "Start of Control-Floor logfile" > /var/log/control-floor/control_floor.log

name_host=`hostname -s`
while read line; 
do
        if [ `echo $line | grep $name_host | wc -l` -eq 1 ]; then
                ownip=`echo $line | awk '{print $1}'`
                break
        fi
done < /etc/hosts

echo "This is my IP - $ownip" >> /var/log/control-floor/control_floor.log
cd /var/www/html/controlfloor
./main run &> /var/log/control-floor/control_floor.log
[root@networks168 ~]# 
```
This way you can have a logfile running in /var/log/

Thanks @nanoscopic, I love this project

**Comment by nanoscopic** [comment]
With the latest updates to CFAgent and the change to do video through CFAgent, this periodic failure over time should no longer occur.

**Comment by Immanuel-GWU** [comment]
I recently pulled the repo and tried it out. This same issue happens for me too @nanoscopic

**Comment by nanoscopic** [comment]
There were lots of issues and they were complex to fix. The fixes for this won't likely be out till the closed-source version of this goes open source again. ( maybe 1-2 years )

The community ( or lack of ) around this seems unlikely to ever be able to figure this out and submit a fixing PR, so I'm closing the issue. It's a real issue, but I don't see the point of having open issues that no one is going to do anything about.
