### ISSUE TITLE
Controlfloor breaks while accessing Device Video

### ISSUE THREAD

**Issue by Chaithra-Menon** [nanoscopic/controlfloor#23]
Pulled latest provider and controlfloor. Built and ran. 
On accessing Device Video, it lead to an error:

2021/03/24 09:17:12 http: panic serving 10.212.134.2:57951: runtime error: invalid memory address or nil pointer dereference
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc0001cc280)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x47760c0, 0x4c45f00)
        /usr/local/go/src/runtime/panic.go:971 +0x499
main.(*ProviderConnection).startImgStream(...)
        controlfloor/provider.go:317
main.handleImgStream(0xc0001b0000, 0xc000376320)
        controlfloor/user.go:138 +0x3b0
main.registerUserRoutes.func1(0xc0001b0000)
        controlfloor/user.go:18 +0x34
github.com/gin-gonic/gin.(*Context).Next(...)
        go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.NeedUserAuth.func1(0xc0001b0000)
        controlfloor/user.go:40 +0xcf
github.com/gin-gonic/gin.(*Context).Next(...)
       go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.Sessions.func1(0xc0001b0000)
        controlfloor/session.go:42 +0xf5
github.com/gin-gonic/gin.(*Context).Next(...)
        go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000392280, 0xc0001b0000)
        go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x2d0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000392280, 0x48f7548, 0xc000598000, 0xc0001e0600)
        go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc000416000, 0x48f7548, 0xc000598000, 0xc0001e0600)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001cc280, 0x48f89e0, 0xc000196300)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b

**Comment by sai-tirunagiri** [comment]
Can you also attach the ios_remote_provider logs at the time of the crash, please? and also can you please indent the logs so that it can be read through.

**Comment by gkrananth** [comment]
i have issue while access to control the iPhone from browser.

Got incoming frame 1020
Got incoming frame 1050
Got incoming frame 1080
INFO[0077] Swiping:279 517 151 517                      
Got incoming frame 1110
INFO[0078] Swiping:128 456 163 394                      
Got incoming frame 1140
INFO[0080] Swiping:230 377 111 377                      
INFO[0080] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
panic: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:50929->127.0.0.1:8102: read: connection reset by peer

goroutine 318 [running]:
main.(*WDA).create_session(0xc000318930, 0x0, 0x0, 0x201, 0x101000004f02ec8)
	/Users/anantharaj/remoteios/ios_remote_provider/wda.go:116 +0x3a5
main.(*WDA).ensureSession(0xc000318930)
	/Users/anantharaj/remoteios/ios_remote_provider/wda.go:75 +0x3a
main.(*WDA).sessionCall(0xc000318930, 0x43fd237, 0x12, 0xc00017a000, 0x19d, 0xc00017a000, 0x19d)
	/Users/anantharaj/remoteios/ios_remote_provider/wda.go:155 +0x456
main.(*WDA).swipe(0xc000318930, 0x117, 0x205, 0x97, 0x205)
	/Users/anantharaj/remoteios/ios_remote_provider/wda.go:297 +0x2a9
main.(*Device).swipe(...)
	/Users/anantharaj/remoteios/ios_remote_provider/device.go:377
main.(*ControlFloor).openWebsocket.func6(0xc000250300, 0xc0003a6000, 0x19, 0x117, 0x205, 0x97, 0x205)
	/Users/anantharaj/remoteios/ios_remote_provider/controlfloor.go:285 +0xa7
created by main.(*ControlFloor).openWebsocket
	/Users/anantharaj/remoteios/ios_remote_provider/controlfloor.go:282 +0x9d8

**Comment by nanoscopic** [comment]
This issue is out of date and its unclear what action would be desired to "correct" this.
Startup with video in current latest code works without described issue.

If a way to cause a problem like above is known / can be explained please create an issue and describe it.

@gkrananth The issue you are describing is entirely different from the issue described by @Chaithra-Menon ; if you still have that issue please raise it in a different github issue, as I am closing this issue as the issue described by @Chaithra-Menon doesn't exist any more.

Essentially, this ticket is solved / fixed. For a different issue please use a different github issue. Thanks.
