### ISSUE TITLE
Golang go.sum errors

### ISSUE THREAD

**Issue by spektant** [nanoscopic/controlfloor#24]
Please list all dependancies as done perviously on Open STF - 
I did not even have go when I try to make the project. As per setup -

Setup Control Floor
git clone https://github.com/nanoscopic/controlfloor.git
cd controlfloor
make

Failures on make - 

.......$ make
go build -o main .
go: github.com/alexedwards/scs/sqlite3store@v0.0.0-20201122155747-696f8e8a5fe2: missing go.sum entry; to add it:
	go mod download github.com/alexedwards/scs/sqlite3store
make: *** [main] Error 1

When I did the suggested - go mod download github.com/alexedwards/scs/sqlite3store

.....$ make
go build -o main .
session.go:8:5: missing go.sum entry for module providing package github.com/alexedwards/scs/v2 (imported by main.go); to add:
	go get main.go
device.go:7:5: missing go.sum entry for module providing package github.com/gin-gonic/gin (imported by main.go); to add:
	go get main.go
dev_tracker.go:5:5: missing go.sum entry for module providing package github.com/gorilla/websocket (imported by main.go); to add:
	go get main.go
db.go:6:5: missing go.sum entry for module providing package github.com/mattn/go-sqlite3 (imported by main.go); to add:
	go get main.go
main.go:9:5: missing go.sum entry for module providing package github.com/nanoscopic/uclop/mod (imported by main.go); to add:
	go get main.go
config.go:7:5: missing go.sum entry for module providing package github.com/nanoscopic/ujsonin/mod (imported by main.go); to add:
	go get main.go
config.go:8:5: missing go.sum entry for module providing package github.com/sirupsen/logrus (imported by main.go); to add:
	go get main.go
db.go:7:5: missing go.sum entry for module providing package xorm.io/xorm (imported by main.go); to add:
	go get main.go
make: *** [main] Error 1

Any suggestions or I am missing more dependancies ?

**Comment by nanoscopic** [comment]
You are the second user who has reported getting an error downloading the sqlite3store module. I did test this in a fresh clone with GOPATH pointed towards a new empty directory, and I had no issue with following the exact steps you've listed here.

It's unclear to me why it is happening as I can't replicate it. If you `go get github.com/alexedwards/scs/sqlite3store` manually, does that work and correct the problem for you?

**Comment by spektant** [comment]
Hi Nano, 

Just short system overview. Clean MACBook Pro with fresh installed Big Sur 2 hours before I tried the setup. Only curl and brew installed in addition. I was missing even go when I checked out the project. That is why I asked for dependency list. 

Looking at it now I see that Brew could not do some of the steps that are required to properly set GO. I used a guide and installed latest version. Checkout In a new folder with go PATH set - 

.............-MacBook-Pro:controlfloor ...............$ make
go build -o main .
go: github.com/alexedwards/scs/sqlite3store@v0.0.0-20201122155747-696f8e8a5fe2: missing go.sum entry; to add it:
	go mod download github.com/alexedwards/scs/sqlite3store
make: *** [main] Error 1

What you suggested - go get github.com/alexedwards/scs/sqlite3store

................-MacBook-Pro:controlfloor .................$ go get github.com/alexedwards/scs/sqlite3store
go get: upgraded github.com/alexedwards/scs/sqlite3store v0.0.0-20201122155747-696f8e8a5fe2 => v0.0.0-20210131110750-3ca38f9a41cc

When I try to do make again - 

...................-MacBook-Pro:controlfloor .................$ make
go build -o main .
session.go:8:5: missing go.sum entry for module providing package github.com/alexedwards/scs/v2 (imported by main.go); to add:
	go get main.go
device.go:7:5: missing go.sum entry for module providing package github.com/gin-gonic/gin (imported by main.go); to add:
	go get main.go
dev_tracker.go:5:5: missing go.sum entry for module providing package github.com/gorilla/websocket (imported by main.go); to add:
	go get main.go
db.go:6:5: missing go.sum entry for module providing package github.com/mattn/go-sqlite3 (imported by main.go); to add:
	go get main.go
main.go:9:5: missing go.sum entry for module providing package github.com/nanoscopic/uclop/mod (imported by main.go); to add:
	go get main.go
config.go:7:5: missing go.sum entry for module providing package github.com/nanoscopic/ujsonin/mod (imported by main.go); to add:
	go get main.go
config.go:8:5: missing go.sum entry for module providing package github.com/sirupsen/logrus (imported by main.go); to add:
	go get main.go
db.go:7:5: missing go.sum entry for module providing package xorm.io/xorm (imported by main.go); to add:
	go get main.go
make: *** [main] Error 1


Bash Profile - 

export GOROOT=/usr/local/go

export GOPATH=$HOME/Documents/Projects/controlfloor

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

**Comment by hdiallo-vl** [comment]
Hi @nanoscopic , do you have a solution for the make failure?
I got the same errors then downloaded the `sqlite3store` but still not solved.
@spektant  do you have an idea?

HELP PLEASE

**Comment by hdiallo-vl** [comment]
I was able to run the `make` command.
You just have to run `go get ` before `make`

**Comment by sonusainier** [comment]
make: Nothing to be done for `all'.

**Comment by nanoscopic** [comment]
This should be corrected by the latest commit. Please `git pull` and try again. Closing. If you still have an issue please reopen with details of updated result.
