### ISSUE TITLE
Controlfloor - historical devices still remains in UI

### ISSUE THREAD

**Issue by kristeedev** [nanoscopic/controlfloor#25]
I had 8 devices in the host initially. Removed 6 devices but controlfloor still shows up 8 devices in the UI. Tried restarting controlfloor main but it still exists.

**Comment by plaguez137** [comment]
They're persisted in the controlfloor/db.sqlite3 file.  Note --> https://github.com/nanoscopic/ios_remote_provider/issues/8#issuecomment-806270233
The easiest solution is to delete the db file, as it will be recreated when you restart CF.

**Comment by nanoscopic** [comment]
Latest updates show a "Ready" column to indicate which devices are actually up and running.
After clicking a device, in the detailed device info, there are also two new fields there which are WDA status and Video App status. When both of those are up, the device can be interacted with normally.

As stated, deleting the DB file can be done any time and clears the devices. You do of course need to restart CF to recreate it.
