### ISSUE TITLE
Golang ujsonin/uclop go.sum error

### ISSUE THREAD

**Issue by aslozhkin** [nanoscopic/controlfloor#26]
I get error at make wda:
mcloud-ios@MacMini ios_remote_provider % make wda                                   
make -C repos/ujsonin gojq && touch bin/gojq
go build -o gojq gojq.go
go: github.com/nanoscopic/uclop@v1.1.0: missing go.sum entry; to add it:
 go mod download github.com/nanoscopic/uclop
make[1]: *** [gojq] Error 1
git clone  repos/WebDriverAgent
fatal: repository 'repos/WebDriverAgent' does not exist
make: *** [repos/WebDriverAgent] Error 128

Also executed manually without errors:
go mod download github.com/nanoscopic/uclop

@nanoscopic what am I doing wrong?

**Comment by nanoscopic** [comment]
This should be corrected by the latest commit. Please `git pull` and try again. Closing. If you still have an issue please reopen with details of updated result.
