### ISSUE TITLE
Back once again

### ISSUE THREAD

**Issue by The-Phoneboy** [nanoscopic/controlfloor#29]
There was no intention to offend anyone...I am trying to rattle your cages as I am inspired and wish to fire ya'll  up...as I was raised...the best way to do that is to piss someone off...rage brings adrenaline...to some clarity.....you may want to beat me with a  football bat... shame me...

Please understand that was not my goal....

I set out to get you attention....I hope I was successful...

it is difficult to join a team capable of greatness if everyone is asleep..

 Stand up and bring the heat...

I will lay claim to nothing save being   nuts enough to get the engine started again and surge across the finish line>

No time like the present

---------------------------------------------------------------------------------------------------------------------

Standards per discussion

---------------------------------------------------------------------------------------------------------------------
iPhone 6 and below..forget about it for now

iPhone 6s is Ground Zero

from experience ..something is rotten there...a corner cut...6s && 6s+ are different animals...given choice...forget about the 6s +

overlooked by most...the SE 1rst gen is a beast...inexpensive  && a workhorse....I will prove that

At our disposal I have

2 x 4
2 x 5s
4 x 6
3 x 6s
1 x 6s+
1 x 7
1 x 8
1 x 12 Mini 1x 12 1x 12 Pro Max

Proof

75 x Legit SE 1rst
10 SE 1rst  iCloud locked for JB testing

3 x iMac
2 x Mac Mini
R720  EsXI VM's for day's

it has an issue I have not had time to sus out>>>it does not like USB..even with a powered card...possible a bios issue

 Capacity for 120 USB Device.. will need more cords

Fiber

Genertor in the works

18 x Pixel XL 2 --- Not all tested

In essence gentlemen.. a Devicefarm (intentional nod the pioneers)

 this is a production environment.... && I have no  issues in shifting usage

This is my contribution

crank out the code...please make sure it compiles....though a bitch to wrap my head around... @David Helkowski organizational methods uniquely suited to our environment due to the rather excessive amount of repos and  it just makes sense...adapting repos/blah as  standard makes sense

dump it on me...define criteria...I will test and be through .. keep in mind that while I grok  logic && workflow...under the hood I am as useless as tits on a boar hog

 Issues -- if you know the answer speak up--help the team..  Nano cannot do it al
------------------------------------------------------------------------------------------------------------
Worth mentioning that I am licensed in both app/play stores as an entity and capable of publishing as such...test flight is blessing

OnBoard?

Let's Light this Candle

wrap up-----I will not apologies for style or who am I ...my words were intentionally designed to rattle your cage>>>that being said.. I sincerely apologize if I offended anyone

This is the Way

peas..Flux
-------------------------------------------------------------------------------------------------------------

**Comment by sai-tirunagiri** [comment]
What's your point? this section is for creating issues related to controlfloor, what is your issue with controlfloor so that the community can contribute to solving it.

**Comment by The-Phoneboy** [comment]
Sorry..nothing happening is an issue in my world...that was my of pointing out that the magik is fading and the talent is going to go somewhere...in my opinion that is valuable contribution to the group..speak up in the slack..contribute.....dig way back in the issues....that is all the world or the community can see... If you have a problem with an old man offering to bitch work for the hotshots..as I see the potential....that sounds lile a personal problem
https://youtu.be/BLPM-P7mNQw

________________________________

**Comment by nanoscopic** [comment]
Closing. This doesn't seem to be an issue.
