### ISSUE TITLE
Android support / Plan to replace DeviceFarmer?

### ISSUE THREAD

**Issue by man4567890** [nanoscopic/controlfloor#32]
Hi @nanoscopic ,
Any plans on getting Android to work on ControlFloor as well, IE total replacement of Device Farmer?

**Comment by nanoscopic** [comment]
Yes, in general ControlFloor is meant to eventually replaced DeviceFarmer entirely. There are no extensive plans on it so far, except for architecting CF such that it should be easy enough to add different support for Android devices.

I say easily but there are a number of things that must be done to make it possible.

The main things to get started:
1. Detect connected devices and fetch their basic info. Easy enough. Can use adb.
2. Show video video from Android device. Plan here is to use srccpy, which can also ->
3. Support control of the device; clicks/swipes/etc

Compared to supporting iOS devices supporting Android devices should actually be very easy.

**Comment by inluxc** [comment]
Hi there, im researching a device farm right now.

srccpy already as control of the device.

**Comment by nanoscopic** [comment]
Yes, srccpy is going to be used to add Android support to CF.

The main focus currently is on iOS as there is no effective open source solution besides this for making an iOS device farm.

The only other iOS open source device farm support I've seen is the "mrx repo" for STF. It's barely documented and has many problems.

**Comment by nanoscopic** [comment]
I'm not sure this will ever happen in public open source ( this project ).

It remains my long term plan ( to re-open-source the current closed-source improved CF and for it to also support Android ) but it is taking so long I'm going to just close this issue for now.

It will happen after the following:
1. I begin to sell the private CF to individuals and smaller companies ( I'm working on that... )
2. Enough re-occurring license buyers are onboard with paying for the product monthly and continuing to do so even if it goes open source again, such that DryArk can still make enough money to exist and work on this project with it open source again.

Who knows how long those two things will happen.
I estimate 1 within the next few months.
I estimate 2 probably in a year or two.
