### ISSUE TITLE
Acess controlfloor from another computer

### ISSUE THREAD

**Issue by yashashetty** [nanoscopic/controlfloor#34]
Hi ,
I was able to bring up controll floor in my local Mac.I want to access it using another machine on a browser .How could I do it .

**Comment by SPrasadT** [comment]
You mean, within the same LAN or from some remote network?

**Comment by yashashetty** [comment]
@SPrasadT using  some remote network

**Comment by nanoscopic** [comment]
You would need to have your machine on a public IP, or having public routable IP forwarded to your machine.

There are a bunch of ways to do this:
1. If your IP address is actually publicly routeable, setup a port forward on your router ( if your ISP allows it ) from some port to the local machine with the IP address CF is running on. This should generally work for most people.
2. Run a paid VPN such as airvpn.org, and setup a port forward on your public exit IP. This will work if your ISP is Natting you and you have no actual public IP.
3. Run some small service in the cloud that forwards requests from itself to your machine.
